name: 'Build App'

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Do the funky linux stuff
        run: sudo dpkg --add-architecture i386  && sudo apt update

      - name: Install Wine
        run: sudo apt-get install wine32

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18.17.x
          cache: yarn

      - name: Install Deps
        uses: borales/actions-yarn@v4
        with:
          cmd: install

      - name: Build Electron App
        uses: borales/actions-yarn@v4
        with:
          cmd: dist

      - name: Install UI Deps
        uses: borales/actions-yarn@v4
        with:
          cmd: install
          dir: gui

      - name: Build UI
        uses: borales/actions-yarn@v4
        with:
          cmd: build
          dir: gui

      - name: Create UI Folder
        run: mkdir dist/win-unpacked/ui

      - name: Copy UI Into Build Folder
        run: cp -r gui/dist/* dist/win-unpacked/ui

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: dist

      - name: Get Version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@v1.3.1

      - name: Create Draft Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          tag_name: ${{ steps.package-version.outputs.current-version}}
          release_name: ${{ steps.package-version.outputs.current-version}} Release
          draft: true
          prerelease: false

      - name: Zip Build Folder
        uses: montudor/action-zip@v1
        with:
          args: zip -qq -r build.zip dist

      - uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./build.zip
          asset_name: ${{ steps.package-version.outputs.current-version}}-Release.zip
          asset_content_type: application/zip